version = "v0.0.3"


# 开发环境数据库配置 - 类型说明作为参考，并非实际的数据库配置，相关DSN请放入.env文件里
[database.dev]
type ="postgresql"
host = "localhost"
port = 5432
user = "postgres"
db_name = "postgres"


# Go客户端配置
# 这里是go程序对前端的页面端口设置
[web.server]
host = "localhost"
port = 8080
timeout = 30
max_idle_conns = 20
max_open_conns = 100
conn_max_lifetime_hours = 1


# Python服务端配置
[agent.server]
host = "localhost"
port = 50051
max_threads = 16
# 这里以MB为单位,默认50M
send_size = 50
receive_size = 50
enable_jwt = true
enable_global_rate_limit = true
global_rate_limit = 100
global_burst = 200
enable_user_rate_limit = true
user_rate_limit = 60
user_burst = 120





# 是否使用本地部署的大模型
[model.use]
chat = false
embedding = false
rerank = false

[model.chat]
host = "127.0.0.1"
token = 8192
name = "qwen"
version = "v1"
port = 18000

[model.embedding]
host = "127.0.0.1"
name = ""
version = "v1"
embedding_dim = 1024
port = 1

[model.rerank]
host = "127.0.0.1"
name = ""
version = "v1"
reranking_dim = 1024
port = 1
