version = "0.0.3"


# 开发环境数据库配置
[database.dev]
type ="postgresql"
host = "localhost"
port = 5432
user = "postgres"
password = "123456"
db_name = "postgres"

# 继承通用配置（TOML本身不支持继承，可在代码中合并）

# 生产环境数据库配置
[database.prod]
type ="postgresql"
host = ""
port = 1234
user = ""
password = ""
db_name = ""

# Python服务端配置
[grpc.server]
host = "0.0.0.0"
port = 50051
max_threads = 16

# Go客户端配置
[grpc.client]
host = "0.0.0.0"
port = 8080

# 是否使用本地部署的大模型
[model.use]
chat = false
embedding = false
rerank = false

[model.chat]
host = "127.0.0.1"
token = 8192
name = "qwen"
version = "v1"
port = 18000

[model.embedding]
host = "127.0.0.1"
name = ""
version = "v1"
embedding_dim = 1024
port = 1

[model.rerank]
host = "127.0.0.1"
name = ""
version = "v1"
reranking_dim = 1024
port = 1
